qqq

diff --git a/debian/kafka/include/etc/confluent/schema_registry/docker/apply-mesos-overrides b/debian/kafka/include/etc/confluent/schema_registry/docker/apply-mesos-overrides
--- a/debian/kafka/include/etc/confluent/schema_registry/docker/apply-mesos-overrides
+++ b/debian/kafka/include/etc/confluent/schema_registry/docker/apply-mesos-overrides
@@ -14,32 +14,11 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-set -o nounset \
-    -o errexit \
-    -o verbose \
-    -o xtrace
+# Mesos DC/OS docker deployments will have HOST and PORT0 
+# set for the proxying of the service.
+# 
+# Use those values provide things we know we'll need.
 
+[ -n "${HOST:-}" ] && [ -z "${SCHEMA_REGISTRY_HOST_NAME:-}" ] && \
+	export SCHEMA_REGISTRY_HOST_NAME=$HOST || true # we don't want the setup to fail if not on Mesos
 
-# Set environment values if they exist as arguments
-if [ $# -ne 0 ]; then
-  echo "===> Overriding env params with args ..."
-  for var in "$@"
-  do
-    export "$var"
-  done
-fi
-
-echo "===> ENV Variables ..."
-env | sort
-
-echo "===> User"
-id
-
-echo "===> Configuring ..."
-/etc/confluent/docker/configure
-
-echo "===> Running preflight checks ... "
-/etc/confluent/docker/ensure
-
-echo "===> Launching ... "
-/etc/confluent/docker/launch
